Repository mash-up-kr/TwoToo_Android, pull requests merged in 2023-06, with the labels that each got.

#65 Home Challenge State 추가 구현
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/HomeKtTest.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/progressbar/TwoTooGoalAchievementProgressbar.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeFlower.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/before/HomeBeforeChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/before/components/HomeBeforeChallengeImage.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/before/components/HomeBeforeChallengeTitle.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/ChallengeStateTypeUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeFlowerData.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeFlowerUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalAchieveData.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalAchieveUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalCountData.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalCountUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalFieldData.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeGoalFieldUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeShoutCountTextData.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeShoutCountTextUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/navigation/HomeNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeBeeButton.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlowerOwnerText.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalField.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeShotCountText.kt
  presenter/src/main/res/drawable/ic_heart.xml
  presenter/src/main/res/drawable/image_challenge_empty.png
  presenter/src/main/res/drawable/image_challenge_response.png
  presenter/src/main/res/values/string.xml
Labels: need review

#68 challenge done 다이어로그 구현
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/SetImageOptionDialog.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/common/Containers.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Shape.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryDialog.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/model/DropDialogTextUiModel.kt
  presenter/src/main/res/values/string.xml
Labels: feature

#82 정원, 툴바 최신 ui 가이드 리소스 사용하도록 수정
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/container/TwoTooScreenContainer.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toolbar/TwoTooBackToolbar.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenComponents.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryComponents.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt
  presenter/src/main/res/drawable-hdpi/challenge_card_ground.png
  presenter/src/main/res/drawable-hdpi/flower_chrysanthemum.png
  presenter/src/main/res/drawable-hdpi/flower_fig.png
  presenter/src/main/res/drawable-hdpi/lose.png
  presenter/src/main/res/drawable-hdpi/tulip.png
  presenter/src/main/res/drawable-xhdpi/challenge_card_ground.png
  presenter/src/main/res/drawable-xhdpi/flower_chrysanthemum.png
  presenter/src/main/res/drawable-xhdpi/flower_fig.png
  presenter/src/main/res/drawable-xhdpi/lose.png
  presenter/src/main/res/drawable-xhdpi/tulip.png
  presenter/src/main/res/drawable-xxhdpi/challenge_card_ground.png
  presenter/src/main/res/drawable-xxhdpi/flower_chrysanthemum.png
  presenter/src/main/res/drawable-xxhdpi/flower_fig.png
  presenter/src/main/res/drawable-xxhdpi/lose.png
  presenter/src/main/res/drawable-xxhdpi/tulip.png
  presenter/src/main/res/drawable-xxxhdpi/challenge_card_ground.png
  presenter/src/main/res/drawable-xxxhdpi/flower_chrysanthemum.png
  presenter/src/main/res/drawable-xxxhdpi/flower_fig.png
  presenter/src/main/res/drawable-xxxhdpi/lose.png
  presenter/src/main/res/drawable-xxxhdpi/tulip.png
  presenter/src/main/res/drawable/back_arrow.xml
  presenter/src/main/res/drawable/ic_back.xml
  presenter/src/main/res/drawable/ic_more.xml
  presenter/src/main/res/drawable/more.xml
  presenter/src/main/res/values/string.xml
Labels: need review

#83 MyPage 스크린추가
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/ui/TwoTooAppKtTest.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/components/MyPageItemList.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/model/MyPageItem.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/navigation/UserNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TopLevelDestination.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooAppState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/user/User.kt
  presenter/src/main/res/values/string.xml
Labels: need review

#86 TwoToo Custom Toast 제작
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toast/TwoTooSnackbar.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
  presenter/src/main/res/values/string.xml
Labels: need review

#91 카메라 사진 찍기 & 앨범 선택에 크롭기능 넣기
  gradle/libs.versions.toml
  presenter/build.gradle.kts
  presenter/src/main/AndroidManifest.xml
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/BottomSheet.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/SetImageOptionDialog.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/util/CreatePhotoFile.kt
  presenter/src/main/res/xml/path_provider.xml
Labels: need review

#84 TwoTooTheme에서 TwoTooColorScheme 적용
  gradle/libs.versions.toml
  presenter/build.gradle.kts
  presenter/src/main/java/com/mashup/twotoo/presenter/MainActivity.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/container/TwoTooScreenContainer.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Theme.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooApp.kt
Labels: need review

#94 온보딩, 챌린지 생성 Navigation
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/SelectFlowerCard.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/navigation/CreateChallengeNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/recommendChallenge/RecommendChanllengeContent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/SendInvitation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/navigation/InviteNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TopLevelDestination.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/NickNameSetting.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoarding.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/NickNameSettingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/OnBoardingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/sdk/theme/KakaoLoginButtonTheme.kt
  presenter/src/main/res/values/string.xml
Labels: need review

#81 History 네비게이션
  presenter/src/main/java/com/mashup/twotoo/presenter/garden/Garden.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/garden/GardenComponents.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/garden/navigation/GardenNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryComponents.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/HistoryScreen.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/datail/HistoryDetailScreen.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/history/navigation/HistoryNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/navigation/HomeNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/navigation/UserNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TopLevelDestination.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooApp.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooAppState.kt
Labels: need review

#101 Feature/add dagger view model
  app/src/main/java/com/mashup/twotoo/Application.kt
  app/src/main/java/com/mashup/twotoo/di/ApplicationComponent.kt
  data/src/main/java/com/mashup/twotoo/di/DataStoreModule.kt
  data/src/main/java/com/mashup/twotoo/di/qualifier/DispatchQualifier.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/HomeKtTest.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/MainActivity.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/DaggerViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenComponentProvider.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ViewModelFactory.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ViewModelFactoryModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ViewModelKey.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ViewModelModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/di/HomeComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/di/HomeModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/navigation/HomeNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/MyPage.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/di/UserComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/di/UserModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/mypage/navigation/UserNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/OnBoardingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooApp.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/ui/TwoTooAppState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/util/ComponentProvider.kt
Labels: help wanted

#110 BottomSheet의 키보드가 항상 올라오도록 변경
  .gitignore
  gradle/libs.versions.toml
  presenter/build.gradle.kts
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/ImageView.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/Authenticate.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/BottomSheet.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/bottomsheet/ShotAndCheer.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/textfield/TextField.kt
  presenter/src/main/res/drawable/empty_image_color_placeholder.xml
  presenter/src/main/res/raw/bottom_sheet.json
  presenter/src/main/res/values/string.xml
Labels: need review

#108 온보딩, 챌린지 생성 Orbit MVI 구현
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallengeState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/CreateChallengeViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/createChallenge/model/ChallengeInfoModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/InviteSideEffect.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/InviteState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/InviteViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/model/InviteType.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/navigation/NickNameSettingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingViewModel.kt
Labels: need review
