Repository mash-up-kr/TwoToo_Android, pull requests merged in 2023-07, with the labels that each got.

#120 챌린지 생성 이전 디자인 리소스 변경
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/ChallengeStateTypeUiModel.kt
  presenter/src/main/res/drawable-hdpi/img_challenge_empty.png
  presenter/src/main/res/drawable-hdpi/img_challenge_request.png
  presenter/src/main/res/drawable-hdpi/img_challenge_response.png
  presenter/src/main/res/drawable-hdpi/img_challenge_termination.png
  presenter/src/main/res/drawable-hdpi/img_challenge_wait.png
  presenter/src/main/res/drawable-xhdpi/img_challenge_empty.png
  presenter/src/main/res/drawable-xhdpi/img_challenge_request.png
  presenter/src/main/res/drawable-xhdpi/img_challenge_response.png
  presenter/src/main/res/drawable-xhdpi/img_challenge_termination.png
  presenter/src/main/res/drawable-xhdpi/img_challenge_wait.png
  presenter/src/main/res/drawable-xxhdpi/img_challenge_empty.png
  presenter/src/main/res/drawable-xxhdpi/img_challenge_request.png
  presenter/src/main/res/drawable-xxhdpi/img_challenge_response.png
  presenter/src/main/res/drawable-xxhdpi/img_challenge_termination.png
  presenter/src/main/res/drawable-xxhdpi/img_challenge_wait.png
  presenter/src/main/res/drawable-xxxhdpi/img_challenge_empty.png
  presenter/src/main/res/drawable-xxxhdpi/img_challenge_request.png
  presenter/src/main/res/drawable-xxxhdpi/img_challenge_response.png
  presenter/src/main/res/drawable-xxxhdpi/img_challenge_termination.png
  presenter/src/main/res/drawable-xxxhdpi/img_challenge_wait.png
Labels: none review

#121 BeforeChallenge에 challenge count visibility추가
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/before/HomeBeforeChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeGoalCount.kt
Labels: none review

#115 Feature/add cheer component
  .gitignore
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/HomeKtTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/beforeChallenge/HomeBeforeChallengeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/both/HomeOngoingBothAuthTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/doNotBoth/HomeOngoingDoNotAuthBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/firstCreateChallenge/HomeOngoingFirstChallengeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyMe/HomeOngoingAuthOnlyMeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyPartner/HomeOngoingAuthOnlyPartnerTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/both/HomeCheerBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/doNotBoth/HomeCheerDoNotBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyMe/HomeCheerOnlyMeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyPartner/HomeCheerOnlyPartner.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/Home.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/ChallengeStateTypeUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeCheerUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/HomeFlowerUiModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/model/flower/Flower.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/navigation/HomeNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/HomeOngoingChallenge.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeCheerSpeechBubble.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlower.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/ongoing/components/HomeFlowerOwnerText.kt
  presenter/src/main/res/drawable-hdpi/ic_cheer_pencil.png
  presenter/src/main/res/drawable-hdpi/img_cheer_partner_empty.png
  presenter/src/main/res/drawable-hdpi/img_home_first_stage_me.png
  presenter/src/main/res/drawable-hdpi/img_home_first_stage_partner.png
  presenter/src/main/res/drawable-xhdpi/ic_cheer_pencil.png
  presenter/src/main/res/drawable-xhdpi/img_cheer_partner_empty.png
  presenter/src/main/res/drawable-xhdpi/img_home_first_stage_me.png
  presenter/src/main/res/drawable-xhdpi/img_home_first_stage_partner.png
  presenter/src/main/res/drawable-xxhdpi/ic_cheer_pencil.png
  presenter/src/main/res/drawable-xxhdpi/img_cheer_partner_empty.png
  presenter/src/main/res/drawable-xxhdpi/img_home_first_stage_me.png
  presenter/src/main/res/drawable-xxhdpi/img_home_first_stage_partner.png
  presenter/src/main/res/drawable-xxxhdpi/ic_cheer_pencil.png
  presenter/src/main/res/drawable-xxxhdpi/img_cheer_partner_empty.png
  presenter/src/main/res/drawable-xxxhdpi/img_home_first_stage_me.png
  presenter/src/main/res/drawable-xxxhdpi/img_home_first_stage_partner.png
  presenter/src/main/res/values/string.xml
Labels: need review

#126 커밋 api , repository 생성
  data/src/main/java/com/mashup/twotoo/datasource/remote/challenge/ChallengeApi.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/challenge/ChallengeDataSource.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/commit/CommitApi.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/commit/CommitDataSource.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/commit/request/CommitNoRequest.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/commit/request/CommitRequest.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/commit/response/Commit.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/view/ViewApi.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/view/ViewDataSource.kt
  data/src/main/java/com/mashup/twotoo/di/ApiModule.kt
  data/src/main/java/com/mashup/twotoo/di/RepositoryModule.kt
  data/src/main/java/com/mashup/twotoo/mapper/ChallengeMapper.kt
  data/src/main/java/com/mashup/twotoo/mapper/CommitMapper.kt
  data/src/main/java/com/mashup/twotoo/repository/ChallengeRepositoryImpl.kt
  data/src/main/java/com/mashup/twotoo/repository/CommitRepositoryImpl.kt
  data/src/main/java/com/mashup/twotoo/repository/ViewRepositoryImpl.kt
  domain/src/main/java/model/challenge/HomeViewDomainModel.kt
  domain/src/main/java/model/commit/request/CommitNoRequestDomainModel.kt
  domain/src/main/java/model/commit/request/CommitRequestDomainModel.kt
  domain/src/main/java/model/commit/response/CommitResponseDomainModel.kt
  domain/src/main/java/repository/ChallengeRepository.kt
  domain/src/main/java/repository/CommitRepository.kt
  domain/src/main/java/repository/ViewRepository.kt
  domain/src/main/java/usecase/view/GetViewHomeUseCase.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/beforeChallenge/HomeBeforeChallengeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/both/HomeOngoingBothAuthTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/doNotBoth/HomeOngoingDoNotAuthBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/firstCreateChallenge/HomeOngoingFirstChallengeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyMe/HomeOngoingAuthOnlyMeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyPartner/HomeOngoingAuthOnlyPartnerTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/both/HomeCheerBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/doNotBoth/HomeCheerDoNotBothTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyMe/HomeCheerOnlyMeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/cheer/onlyPartner/HomeCheerOnlyPartner.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/home/HomeSideEffectHandler.kt
Labels: none review

#138 Bearer prefix 추가 & getAccessToken runCatching wrap
  data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt
Labels: none review

#141 Feature/sign in
  app/src/main/java/com/mashup/twotoo/Application.kt
  app/src/main/java/com/mashup/twotoo/di/ApplicationComponent.kt
  data/src/main/java/com/mashup/twotoo/datasource/local/UserPreferenceDataSource.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/UserApi.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/UserDataSource.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/request/UserAuthRequest.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/request/UserNickNameRequest.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/PartnerInfoResponse.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/UserAuthResponse.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/UserInfoResponse.kt
  data/src/main/java/com/mashup/twotoo/di/ApiModule.kt
  data/src/main/java/com/mashup/twotoo/di/DataStoreModule.kt
  data/src/main/java/com/mashup/twotoo/di/RepositoryModule.kt
  data/src/main/java/com/mashup/twotoo/mapper/UserMapper.kt
  data/src/main/java/com/mashup/twotoo/repository/UserDataStoreRepositoryImpl.kt
  data/src/main/java/com/mashup/twotoo/repository/UserRepositoryImpl.kt
  domain/src/main/java/model/challenge/CreateChallengeDomainModel.kt
  domain/src/main/java/model/user/PartnerInfoDomainModel.kt
  domain/src/main/java/model/user/UserAuthRequestDomainModel.kt
  domain/src/main/java/model/user/UserAuthResponseDomainModel.kt
  domain/src/main/java/model/user/UserInfoDomainModel.kt
  domain/src/main/java/model/user/UserNickNameDomainModel.kt
  domain/src/main/java/repository/UserDataStoreRepository.kt
  domain/src/main/java/repository/UserRepository.kt
  domain/src/main/java/usecase/token/GetKaKaoAccessTokenUseCase.kt
  domain/src/main/java/usecase/token/SetKaKaoAccessTokenUseCase.kt
  domain/src/main/java/usecase/user/GetUserNoUseCase.kt
  domain/src/main/java/usecase/user/SetNickNameUseCase.kt
  domain/src/main/java/usecase/user/SetUserNoUseCase.kt
  domain/src/main/java/usecase/user/UserAuthUseCase.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenComponentProvider.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/di/InviteComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/di/InviteModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSettingViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSideEffect.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/di/NickNameSettingComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/di/NickNameSettingModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/navigation/NickNameSettingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoarding.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingPagerContent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnboardingSideEffect.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/di/OnboardingComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/di/OnboardingModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/model/OnboardingState.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/OnBoardingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/util/KaKaoAuthFlow.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/util/Logging.kt
Labels: help wanted, need review

#173 [fix] : change toast background & text color
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/firstCreateChallenge/HomeOngoingFirstChallengeTest.kt
  presenter/src/androidTest/java/com/mashup/twotoo/presenter/home/ongoingChallenge/auth/onlyPartner/HomeOngoingAuthOnlyPartnerTest.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/component/toast/TwoTooSnackbar.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/designsystem/theme/Color.kt
Labels: none review

#161 유저 정보 DataStore 저장
  data/src/main/java/com/mashup/twotoo/datasource/local/UserPreferenceDataSource.kt
  data/src/main/java/com/mashup/twotoo/datasource/remote/user/response/UserAuthResponse.kt
  data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt
  data/src/main/java/com/mashup/twotoo/repository/UserDataStoreRepositoryImpl.kt
  domain/src/main/java/model/user/UserAuthResponseDomainModel.kt
  domain/src/main/java/repository/UserDataStoreRepository.kt
  domain/src/main/java/usecase/token/GetAccessTokenUseCase.kt
  domain/src/main/java/usecase/token/SetAccessTokenUseCase.kt
  domain/src/main/java/usecase/user/GetPreferenceUserInfoUseCase.kt
  domain/src/main/java/usecase/user/GetUserNoUseCase.kt
  domain/src/main/java/usecase/user/SetPreferenceUserInfoUseCase.kt
  domain/src/main/java/usecase/user/SetUserNoUseCase.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/di/NickNameSettingModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/OnBoardingViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/di/OnboardingModule.kt
  presenter/src/test/java/com/mashup/twotoo/presenter/home/repository/FakeUserDataStoreRepository.kt
Labels: help wanted, need review

#167 SplashScreen 구현
  app/src/main/AndroidManifest.xml
  app/src/main/ic_app_icon-playstore.png
  app/src/main/java/com/mashup/twotoo/Application.kt
  app/src/main/java/com/mashup/twotoo/di/ApplicationComponent.kt
  app/src/main/res/drawable/img_app_icon.png
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon.xml
  app/src/main/res/mipmap-anydpi-v26/ic_app_icon_round.xml
  app/src/main/res/mipmap-hdpi/ic_app_icon.webp
  app/src/main/res/mipmap-hdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_app_icon_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_app_icon_round.webp
  app/src/main/res/values-v31/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/ic_app_icon_background.xml
  data/src/main/java/com/mashup/twotoo/di/NetworkModule.kt
  data/src/main/java/com/mashup/twotoo/repository/UserDataStoreRepositoryImpl.kt
  domain/src/main/java/model/user/UserNickNameDomainModel.kt
  domain/src/main/java/repository/UserDataStoreRepository.kt
  domain/src/main/java/usecase/user/GetIsSendInvitationUseCase.kt
  domain/src/main/java/usecase/user/GetPreferenceUserInfoUseCase.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenComponentProvider.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/di/ScreenModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/SendInvitation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/WaitingAcceptPair.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/invite/navigation/InviteNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TopLevelDestination.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/navigation/TwoTooNavHost.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/nickname/NickNameSetting.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/onboarding/navigation/OnBoardingNavigation.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/SplashModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/SplashScreen.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/SplashSideEffect.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/SplashViewModel.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/di/SplashComponent.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/di/SplashModule.kt
  presenter/src/main/java/com/mashup/twotoo/presenter/splash/navigation/SplashNavigation.kt
  presenter/src/main/res/drawable-hdpi/img_splash.png
  presenter/src/main/res/drawable-xhdpi/img_splash.png
  presenter/src/main/res/drawable-xxhdpi/img_splash.png
  presenter/src/main/res/drawable-xxxhdpi/img_splash.png
  presenter/src/main/res/values/string.xml
  presenter/src/test/java/com/mashup/twotoo/presenter/home/repository/FakeUserDataStoreRepository.kt
Labels: need review
